/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0272d242-06d9-4c71-8577-3a0acac97cd2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DKzeBd5SN",
    "aws_user_pools_web_client_id": "78j1ufisqdamn93g5tcsi8m9f8",
    "oauth": {}
};


export default awsmobile;
